### ISSUE TITLE
ModuleNotFoundError: tensorflow.contrib

### ISSUE THREAD

**Issue by SomethingGeneric** [shawwn/openai-server#1]
In https://github.com/shawwn/openai-server/blob/master/openai_server/gpt/model.py#L3 , it would appear that the tensorflow library doesn't have `.contrib` anymore? Possibly related to a version change?

**Comment by waundme** [comment]
You must downgrade tensorflow to 1.15.

You must also install ftfy (or add it to requirements.txt) and downgrade sanic to 21.12.2, otherwise openai-server won't even start.

**Comment by SomethingGeneric** [comment]
Do you mean tensorflow `1.15.0` ? If so, that's what the requirements file already says

**Comment by SomethingGeneric** [comment]
Oh wait it's a tensorflow 1 only thing. Got it

**Comment by waundme** [comment]
Yes, and in order to install tensorflow==1.15 you may have to downgrade python to 3.7.

**Comment by SomethingGeneric** [comment]
Thanks! pyenv got me closer.
